root_path= os.getcwd() + "/../"
print("root_path: "+ root_path)

cpp_options=["-g", "-o0", "-std=gnu++17"]
cpp_path=[
    os.path.join(root_path, "skynet-master"),
    os.path.join(root_path, "spdlog-1.17.0"),
    os.path.join(root_path, "muduo-master"),
]

env = Environment(CCFLAGS = cpp_options, CPPPATH = cpp_path)   #全局环境变量

env.Program("App","./main.cpp")

bld = Builder
{
    
}